name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ivaldoj/filosofos

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build (make)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y build-essential
        make

    - name: Quick smoke test
      run: |
        timeout 3s ./filosofos || true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: ${{ github.event_name == 'push' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push (Docker)
      if: ${{ github.event_name == 'push' }}
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Show image tag used
      run: echo "Pushed: $IMAGE_NAME:latest and $IMAGE_NAME:${GITHUB_SHA}"
